// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3niOkpLdNCGPv8r_iQhVmufa9aYK3ywM',
    appId: '1:294296572688:web:37b0eef84725f99a868b95',
    messagingSenderId: '294296572688',
    projectId: 'carbon-check-field',
    authDomain: 'carbon-check-field.firebaseapp.com',
    storageBucket: 'carbon-check-field.firebasestorage.app',
    measurementId: 'G-60PLX2B5PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xjOKRaR79-PEUbv0ojHRpsZg5YkRUFE',
    appId: '1:294296572688:android:71c703aca37d792f868b95',
    messagingSenderId: '294296572688',
    projectId: 'carbon-check-field',
    storageBucket: 'carbon-check-field.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcq0B3IH_3JcRBzSvRbHXNY7ZLZ0C4CIQ',
    appId: '1:294296572688:ios:5550a9822de3f614868b95',
    messagingSenderId: '294296572688',
    projectId: 'carbon-check-field',
    storageBucket: 'carbon-check-field.firebasestorage.app',
    iosBundleId: 'com.carboncheck.field',
  );
}

