steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/ml-orchestrator"
      - "-f"
      - "orchestrator/Dockerfile"
      - "."

images:
  - "gcr.io/$PROJECT_ID/ml-orchestrator"
